# Arrays and Loops

## Problem 1

Import Numpy 

a) Create an array of 50 ones called $x$.

b) Create an array from 1-20 with 50 equally-spaced elements two different ways (using a loop and a single command). Call the two arrays $y$ and $z$.

c) Subtract $y$ from $z$ and report the sum of the absolute difference of each element to show that they are the same.


# A.)

In [1]:
import numpy as np
x = np.ones(50)

# B.)

In [2]:
y = np.zeros(50)
interval = 19/49

for i in range(50):
    y[i] = i * interval + 1

print(y)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


# C.)

In [3]:
z = np.linspace(1,20,50)
print(z)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [4]:
absolute_sum_of_difference = np.sum(abs(z-y))
print(absolute_sum_of_difference)

0.0


## Problem 2

import the python package "random"

a) Create a matrix, $M$, as a 1x1 numpy array of value 1

b) Using a while loop, append a random integer between 1 and 10 to the end of matrix $M$ until the last element is a 7.

c) Report the number of elements in $M$ and the mean value of the elements after the loop.

d) Also, because a while loop is easily susceptible to infinite loops, create a variable $i$ to keep track of how many times you have gone through the while loop. If $i$ exceeds 30, immediately exit the while loop. Don't report the matrix size using $i$.

You may need to search online (e.g. Google) how to create a random integer using the random package and how to append elements to a numpy array. 

# A.)

In [17]:
import random as rand

M = np.ones(1)
print("Original array ==>> ",M)

i = 0
while M[-1] != 7:
    
    i += 1
    
    if i > 30:
        break
        
    randnum = rand.randint(1,10)
    M = np.append(M,randnum) 
    
    
    
print("\n",M,"\n")
print("Lenght of M = ",len(M))
print("Mean of M = ", M.mean())

Original array ==>>  [1.]

 [1. 5. 5. 8. 8. 5. 8. 3. 9. 5. 2. 9. 9. 1. 5. 6. 5. 4. 3. 6. 5. 2. 4. 9.
 5. 2. 4. 1. 9. 9. 6.] 

Lenght of M =  31
Mean of M =  5.258064516129032


## Problem 3

Using the following array, $a$:

Reshape the array to a 5x5 matrix (using a numpy command)

Loop through each element of the array. If the element value is 5 or 8, print the element index. Also, keep track of how many 5s and 8s there are with variable $k$. Print $k$. If the element value is a 1, print "You win!"

In [18]:
a = np.array([  8.,3.,10.,8.,2.,2.,10.,10.,5.,10.,2.,10.,9.,10.,9.,4.,2.,8.,7.,4.,1.,4.,5.,6.,6.])
a = a.reshape(5,5)
k = [0,0]
print(a)
for i in np.arange(np.size(a,0)):
    for j in np.arange(np.size(a,1)):
        if a[i,j] == 1:
            print("\nYou Win!\n")
        if a[i,j] == 5:
            k[0] += 1
            print(f"{a[i,j]} at position ({i},{j})")
        elif a[i,j] == 8:
            print(f"{a[i,j]} at position ({i},{j})")
            k[1] += 1
            
print(f"\nTotal 5's ==>{k[0]} \nTotal 8's ==>{k[1]}")

[[ 8.  3. 10.  8.  2.]
 [ 2. 10. 10.  5. 10.]
 [ 2. 10.  9. 10.  9.]
 [ 4.  2.  8.  7.  4.]
 [ 1.  4.  5.  6.  6.]]
8.0 at position (0,0)
8.0 at position (0,3)
5.0 at position (1,3)
8.0 at position (3,2)

You Win!

5.0 at position (4,2)

Total 5's ==>2 
Total 8's ==>3


## Problem 4

For the following arrays (matrices and vectors):

$A = \begin{bmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{bmatrix}$

$x = \begin{bmatrix}
1\\ 
3\\ 
4
\end{bmatrix}$

$B = \begin{bmatrix}
-0.1 & -0.2 & -0.3\\ 
3 & 10 & 2\\ 
4 & 2 & 0.5
\end{bmatrix} $

Perform the following operations:

a) $A \circ B$ (element-wise multiplication)

b) $A \bullet B$ (dot product multiplication)

c) $A \times B$ (cross product multiplication)

d) $A \bullet x$

e) $A^{-1} \bullet B$

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([[1],[3],[4]])
B = np.array([[-0.1,-0.2,-0.3],[3,10,2],[4,2,0.5]])

In [8]:
print(A*B) #element wise multiplication

[[-0.1 -0.4 -0.9]
 [12.  50.  12. ]
 [28.  16.   4.5]]


In [9]:
print(np.dot(A,B))

[[17.9 25.8  5.2]
 [38.6 61.2 11.8]
 [59.3 96.6 18.4]]


In [10]:
print(np.cross(A,B))

[[ 1.11022302e-16 -5.55111512e-17  0.00000000e+00]
 [-5.00000000e+01  1.00000000e+01  2.50000000e+01]
 [-1.40000000e+01  3.25000000e+01 -1.80000000e+01]]


In [11]:
print(np.dot(A,x))

[[19]
 [43]
 [67]]


In [12]:
inv_A = np.linalg.inv(A)
print(np.dot(inv_A, B))

[[ 9.45755922e+15  8.19655132e+16  1.71136786e+16]
 [-1.89151184e+16 -1.63931026e+17 -3.42273572e+16]
 [ 9.45755922e+15  8.19655132e+16  1.71136786e+16]]
